//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace Model
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Cards>();
                db.CreateTable<CardTypes>();
                db.CreateTable<CustomSets>();
                db.CreateTable<Decks>();
                db.CreateTable<DeckTypes>();
                db.CreateTable<Templates>();
            }
        }
    }
    public partial class Cards
    {
        [PrimaryKey, AutoIncrement]
        public Int64 CardId { get; set; }
        
        [MaxLength(254)]
        [NotNull]
        public String CardName { get; set; }
        
        [MaxLength(254)]
        public String CardDisplayName { get; set; }
        
        public Int32? CardDisplayNameFont { get; set; }
        
        [MaxLength(254)]
        public String CardDisplayNameSub { get; set; }
        
        public Int32? CardDisplayNameSubFont { get; set; }
        
        public Int32? CardTypeId { get; set; }
        
        [NotNull]
        public Int64 TemplateId { get; set; }
        
        [MaxLength(254)]
        public String PowerPrimary { get; set; }
        
        [MaxLength(254)]
        public String PowerSecondary { get; set; }
        
        [MaxLength(4)]
        public String AttributeCost { get; set; }
        
        [MaxLength(4)]
        public String AttributeAttack { get; set; }
        
        [MaxLength(4)]
        public String AttributeRecruit { get; set; }
        
        [MaxLength(4)]
        public String AttributePiercing { get; set; }
        
        [MaxLength(254)]
        public String AttributeVictoryPoints { get; set; }
        
        [MaxLength(500)]
        public String CardText { get; set; }
        
        public Int32? CardTextFont { get; set; }
        
        public Int32? NumberInDeck { get; set; }
        
        [MaxLength(254)]
        public String ArtWorkFile { get; set; }
        
        [MaxLength(254)]
        public String ExportedCardFile { get; set; }
        
        public Int32? DeckId { get; set; }
        
        public Int32? TeamIconId { get; set; }
        
        public Int32? PowerPrimaryIconId { get; set; }
        
        public Int32? PowerSecondaryIconId { get; set; }
        
    }
    
    public partial class CardTypes
    {
        [PrimaryKey, AutoIncrement]
        public Int64 CardTypeId { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String CardTypeName { get; set; }
        
        [MaxLength(50)]
        public String CardTypeDisplayName { get; set; }
        
        public Int32? DeckTypeId { get; set; }
        
    }
    
    public partial class CustomSets
    {
        [PrimaryKey, AutoIncrement]
        public Int64 SetId { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String SetName { get; set; }
        
        [MaxLength(254)]
        public String SetWorkPath { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String SetDisplayName { get; set; }
        
        [NotNull]
        public DateTime DateCreated { get; set; }
        
        public DateTime? DateUpdated { get; set; }
        
    }
    
    public partial class Decks
    {
        [PrimaryKey, AutoIncrement]
        public Int64 DeckId { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String DeckName { get; set; }
        
        [MaxLength(50)]
        public String DeckDisplayName { get; set; }
        
        public Int32? DeckTypeId { get; set; }
        
        public Int32? TeamIconId { get; set; }
        
        public Int32? SetId { get; set; }
        
    }
    
    public partial class DeckTypes
    {
        [PrimaryKey, AutoIncrement]
        public Int64 DeckTypeId { get; set; }
        
        [MaxLength(50)]
        public String DeckTypeName { get; set; }
        
    }
    
    public partial class Templates
    {
        [PrimaryKey, AutoIncrement]
        public Int64 TemplateId { get; set; }
        
        [MaxLength(50)]
        public String TemplateName { get; set; }
        
        [MaxLength(50)]
        public String TemplateDisplayName { get; set; }
        
        [MaxLength(254)]
        public String RectXArray { get; set; }
        
        [MaxLength(254)]
        public String RectYArray { get; set; }
        
        public Int32? CardWidth { get; set; }
        
        public Int32? CardHeight { get; set; }
        
        [MaxLength(254)]
        public String FrameImage { get; set; }
        
        [MaxLength(254)]
        public String CostImage { get; set; }
        
        [MaxLength(254)]
        public String TextImage { get; set; }
        
        [MaxLength(254)]
        public String UnderlayImage { get; set; }
        
        public Boolean? FormShowTeam { get; set; }
        
        public Boolean? FormShowPowerPrimary { get; set; }
        
        public Boolean? FormShowPowerSecondary { get; set; }
        
        public Boolean? FormShowAttributes { get; set; }
        
        public Boolean? FormShowAttributesCost { get; set; }
        
        public Boolean? FormShowAttributesRecruit { get; set; }
        
        public Boolean? FormShowAttributesAttack { get; set; }
        
        public Boolean? FormShowAttributesPiercing { get; set; }
        
        public Boolean? FormShowVictoryPoints { get; set; }
        
        public Boolean? FormShowAttackCost { get; set; }
        
    }
    
}
